### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by richeal11** [Anjaan-g/Nepali-Music-Genre-Classification-using-MFCC-and-CNN#7]
Dai , source code dina milxa?

**Comment by Anjaan-g** [comment]
@richeal11  K ko lagi ho?

**Comment by richeal11** [comment]
Music genre classification using cnn

**Comment by Anjaan-g** [comment]
Tyo ta buje k purpose ko lagi chaiyo code?

**Comment by richeal11** [comment]
Minor project ko lagi colz ma

**Comment by Anjaan-g** [comment]
Can I get the details of you and your college and what you are trying to do here?
